import { Manrope } from "next/font/google";
import "./globals.css";

const monrapeSans = Manrope({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "ochiroo is world",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monrapeSans.variable}  antialiased`}>{children}</body>
    </html>
  );
}
